/**
 * MermaidEditor — text-in-left, live-SVG-out-right.
 *
 * File is plain mermaid source (`.mmd`). Debounced render (250ms) so
 * fast typing doesn't stall the main thread on every keystroke. Each
 * render call gets a unique id (mermaid namespaces its <g> ids and
 * complains if collisions happen when you swap the source in place).
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import mermaid from 'mermaid'

export interface MermaidEditorProps {
  value: string
  onChange: (data: string) => void
  className?: string
}

// One-time init. Suppresses mermaid's built-in error rendering so we
// control the error UI ourselves and users see plain text instead of a
// scary red bomb icon.
let mermaidInitialised = false
function ensureInit(): void {
  if (mermaidInitialised) return
  mermaid.initialize({
    startOnLoad: false,
    theme: 'default',
    securityLevel: 'strict',
    suppressErrorRendering: true
  })
  mermaidInitialised = true
}

let renderCounter = 0

export function MermaidEditor({
  value,
  onChange,
  className
}: MermaidEditorProps): JSX.Element {
  const [source, setSource] = useState(value)
  const [svg, setSvg] = useState<string>('')
  const [error, setError] = useState<string | null>(null)
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const onChangeRef = useRef(onChange)
  onChangeRef.current = onChange

  useEffect(() => {
    ensureInit()
  }, [])

  // Fold external `value` changes (file switch, external write) into
  // the local buffer without triggering onChange.
  useEffect(() => {
    setSource(value)
  }, [value])

  // Debounced render. We render into a detached container-id string
  // that mermaid uses internally — the returned SVG is what we inject.
  const render = useCallback(async (text: string) => {
    const trimmed = text.trim()
    if (!trimmed) {
      setSvg('')
      setError(null)
      return
    }
    try {
      const id = `mermaid-preview-${++renderCounter}`
      const result = await mermaid.render(id, trimmed)
      setSvg(result.svg)
      setError(null)
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    }
  }, [])

  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current)
    debounceRef.current = setTimeout(() => {
      void render(source)
    }, 250)
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current)
    }
  }, [source, render])

  const handleChange = useCallback(
    (next: string) => {
      setSource(next)
      onChangeRef.current(next)
    },
    []
  )

  const previewNode = useMemo(() => {
    if (error) {
      return (
        <div
          style={{
            padding: 16,
            color: 'var(--color-error, #ef4444)',
            fontFamily: 'var(--font-mono)',
            fontSize: 12,
            whiteSpace: 'pre-wrap'
          }}
        >
          {error}
        </div>
      )
    }
    if (!svg) {
      return (
        <div style={{ padding: 16, color: 'var(--text-tertiary)', fontSize: 13 }}>
          在左侧输入 Mermaid 语法开始预览
        </div>
      )
    }
    // svg is generated by mermaid.render from user text; mermaid v11
    // with securityLevel:'strict' escapes user text before inlining, so
    // the resulting SVG contains no active content.
    return (
      <div
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: svg }}
        style={{ padding: 16, display: 'flex', justifyContent: 'center' }}
      />
    )
  }, [svg, error])

  return (
    <div
      className={`mermaid-editor-wrapper ${className || ''}`}
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        background: 'var(--bg-primary)'
      }}
    >
      <textarea
        value={source}
        onChange={(e) => handleChange(e.target.value)}
        spellCheck={false}
        placeholder="graph TD\n  A --> B"
        style={{
          flex: 1,
          minWidth: 200,
          height: '100%',
          border: 'none',
          outline: 'none',
          resize: 'none',
          padding: 16,
          fontFamily: 'var(--font-mono)',
          fontSize: 13,
          lineHeight: 1.6,
          color: 'var(--text-primary)',
          background: 'var(--bg-primary)',
          borderRight: '1px solid var(--border-light)',
          boxSizing: 'border-box',
          tabSize: 2
        }}
      />
      <div
        style={{
          flex: 1,
          minWidth: 200,
          height: '100%',
          overflow: 'auto',
          background: 'var(--bg-secondary)'
        }}
      >
        {previewNode}
      </div>
    </div>
  )
}

export default MermaidEditor
