export const IPC = {
  FILE_READ: 'file:read',
  FILE_READ_META: 'file:readMeta',
  FILE_WRITE: 'file:write',
  FILE_WRITE_GUARDED: 'file:writeGuarded',
  FILE_CREATE: 'file:create',
  FILE_DELETE: 'file:delete',
  FILE_RENAME: 'file:rename',
  FILE_TREE: 'file:tree',
  FILE_MOVE: 'file:move',
  FILE_OPEN_EXTERNAL: 'file:openExternal',
  /** Broadcast event name (not invoked). Payload: FileChangedEvent. */
  FILE_CHANGED_EVENT: 'file:changed',
  /** Broadcast event when the file tree structure changes. Payload: NoteFile[]. */
  FILE_TREE_CHANGED_EVENT: 'file:treeChanged',
  WINDOW_PIN: 'window:pin',
  WINDOW_UNPIN: 'window:unpin',
  WINDOW_SET_OPACITY: 'window:setOpacity',
  WINDOW_TOGGLE_PIN: 'window:togglePin',
  WINDOW_OPEN_NOTE: 'window:openNote',
  WINDOW_CLOSE: 'window:close',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_SET_AUTO_COLLAPSE: 'window:setAutoCollapse',
  WINDOW_AUTO_LAUNCH: 'window:autoLaunch',
  PLUGIN_LIST: 'plugin:list',
  PLUGIN_INSTALL: 'plugin:install',
  PLUGIN_UNINSTALL: 'plugin:uninstall',
  PLUGIN_ACTIVATE: 'plugin:activate',
  PLUGIN_DEACTIVATE: 'plugin:deactivate',
  /** Persist the user's on/off choice for a builtin plugin. */
  PLUGIN_SET_ENABLED: 'plugin:setEnabled',
  PLUGIN_LOAD_LOCAL: 'plugin:loadLocal',
  PLUGIN_GET_MANIFEST: 'plugin:getManifest',
  PLUGIN_OPEN_DEV_GUIDE: 'plugin:openDevGuide',
  PLUGIN_GET_FORMAT_MAP: 'plugin:getFormatMap',
  /** Broadcast event when the extension → renderer map changes. */
  PLUGIN_FORMAT_MAP_CHANGED_EVENT: 'plugin:formatMapChanged',
  AI_GENERATE: 'ai:generate',
  AI_CHAT: 'ai:chat',
  AI_TRANSCRIBE: 'ai:transcribe',
  AI_CANCEL: 'ai:cancel',
  AI_SETTINGS: 'ai:settings',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  DIALOG_OPEN_FILE: 'dialog:openFile',
  DIALOG_OPEN_DIRECTORY: 'dialog:openDirectory',
  DIALOG_SAVE_FILE: 'dialog:saveFile',
  APP_GET_VERSION: 'app:getVersion',
  APP_GET_PATHS: 'app:getPaths'
} as const

export type IPCChannel = (typeof IPC)[keyof typeof IPC]
